### ISSUE TITLE
Import code and prepare data in new file structure

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#1]
@handbury @mollyschnell @rakhkovs @diamondr @moosedube ,

The goal of this issue is to get the code set up and prepare the data in the new file structure so that everybody can start using it. There are continued delays with Booth IT, but JP is working on it.
I am about to push the existing ADD code and lyx file to the master repository. I then will modify it further to make it work in the new file structure. 
Once we finish this, we can move on to the analysis.

A few notes on using Issues:
* All Assignees and all people who are @ mentioned will receive an email every time somebody posts to a thread. 
* If you’d like to add something, you can respond by email, but it’s slightly better if you click through to this web page and post here directly. 
* Once the goal is achieved, we’ll close this issue using the button below.

**Comment by diamondr** [comment]
How do I reference an issue when I commit?

**Comment by huntallcott** [comment]
Write the issue number preceded by # in your commit message, as in the example I'm pasting below:
![image](https://user-images.githubusercontent.com/23505296/41427490-1ff2f8fc-6fd5-11e8-8ece-8957d67bd801.png)
