### ISSUE TITLE
Re-run drivetime script

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#10]
@diamondr , last week I think we talked about you re-running the drive time perl script. With @handbury's help, I have prepped the data and it is ready for you to run. 
Please see $Externals/Calculations/Homescan/StoreHouseStoreHouseLatLong.csv.
Then you are supposed to deliver $Externals/Data/DriveTime/drivetimes.csv, hopefully in the same format as the file was from a few years ago in our old file system, including the location IDs so that I can merge the data correctly.
Many thanks in advance.

**Comment by diamondr** [comment]
This is running.

**Comment by huntallcott** [comment]
@diamondr thanks for doing this. Quick questions:
1. Is there still a restriction on the number of queries per day? If so, how long will this take?
2. I am looking at drivetimes_2018.csv which I think you are creating. Am I correct that the column headers are wrong? The first column is Store_Location_ID, not the second column?

Thanks again.

**Comment by diamondr** [comment]
Oops yes, you are correct about column headers. Also the cap is 100k queries per calendar day. We have 200k right now. I'll kick it off again tomorrow. we have 2.6 million in the file... Are you restricting the store pairs to nearby stores only? Could we restrict to only stores within 50 miles?

**Comment by diamondr** [comment]
Ah I see you're already restricting to 15 miles or less.

**Comment by diamondr** [comment]
I just looked more into the google caps and it appears the caps are higher now than they used to be. It will cost about $2000 to do all this geocoding, but tis running now.

**Comment by huntallcott** [comment]
@diamondr , can you give an update on this and how it's looking? I think the original file has 2.6 million rows and the current csv file has 1.0 million rows, so not done yet? Just checking in. Thanks.

**Comment by diamondr** [comment]
We're at 1.6 mill. I think right now. It crashes randomly and then i have
to manually restart. It should be done by the end to the week if not sooner.

**Comment by diamondr** [comment]
Done!

**Comment by huntallcott** [comment]
Thanks for doing this, I really appreciate it.
