### ISSUE TITLE
Revise stylized facts

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#12]
@mollyschnell @handbury @diamondr ,
The goal of this issue is to revise the stylized facts section.
In our 6-20-2018 meeting, we agreed to keep the price differences in the appendix, so I will do that.
We also agreed that I would look into residualizing the stylized facts figures of age and Calorie Need, so that income is a better measure of SES. I am doing that now.
I will condense the text a bit but otherwise will leave as is. 
Is there anything else you'd change here?
If not I'll update later today.

**Comment by huntallcott** [comment]
@mollyschnell @handbury @diamondr ,
I have updated the stylized facts figures today per the above and just pushed to the master.
@handbury @mollyschnell @diamondr a couple of things to be aware of:
1. I defined a new global called SESCtls that has age and household size (in calorie-equivalent adults). I'm using this to residualize income in order to present income as a measure of SES. @handbury can you use the same global in your code? 
2. I am using household sample average real income now that we are residualizing of $SESCtls, and reporting statistics by quartile. @diamondr I think that you should do this for the demand estimates as well if that's OK? This variable is HHAvIncome in Prepped-Household-Panel.dta.
3. I am still working on the text. One thing to take note of is that I am moving to automatically import results into the lyx file so that we don't need to re-check things if we change the HealthIndex or something else. You can see an example of this at the beginning of Section 3.1 of the lyx file.
I hope to finish this ASAP.

**Comment by diamondr** [comment]
Ok. I can rerun the model with the new income definitions. The model is
very slow to estimate. Will probably be another week before we get new
estimates.

**Comment by huntallcott** [comment]
@diamondr : 
1. I am sorry for the change. 
2. You might wait on re-estimating in case we discuss further and something else changes.
3. In the interim, I don't think we'll do anything that will change the estimates much, and I wonder if it's worth working on the revised writeup etc. if you have time?
Let me know what you think. Happy to discuss.

**Comment by huntallcott** [comment]
@mollyschnell ,
@handbury said that you were open to looking at the stylized facts section. I had said last week that I thought that upon some reflection, the text I had written in the ADD stylized facts section might have a bit of fluff. Your fresh eyes, plus a sense of what HRS had done, might help. 
Do you want to take a look at the stylized facts section and maybe track some changes or leave some comments with your thoughts?

**Comment by mollyschnell** [comment]
@huntallcott: Happy to do so! I'll work on streamlining the SF section (tracking changes in the LyX document). Let me know when you think the RF section is good to go, and I can take a look there as well.

**Comment by Rahkovsky** [comment]
@huntallcott I tried to update acknowledgment and disclaimer footnote, but I could not push changes to master. I have the following error: 

Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

Should I create a fork with my changes?

**Comment by mollyschnell** [comment]
@huntallcott: I'm in the same position as @moosedube. Do we think there's a good way to deal with this? I'd prefer not to delete 2.3 and reinstall 2.2 since my other projects are in 2.3 (but certainly can if that's the best workaround!).

**Comment by mollyschnell** [comment]
@huntallcott: Never mind! You can have multiple versions of LyX on your computer, so I reinstalled 2.2 to use with this project. @moosedube: you can download 2.2.4 here https://ftp.lip6.fr/pub/lyx/bin/2.2.4/.

**Comment by huntallcott** [comment]
@mollyschnell thanks for your great edits.
* I accepted all of them, except that I deleted the numbering (1), (2), (3), (4) when describing figure 1.
* On the map, we (ADD) struggled with that as well, but (i) it's a really nice figure, and (ii) we thought we need it for the movers analysis. I am going to look into whether it flows well when included at the beginning of 4.2.
* For consistency, what if we all use the phrases “dietary quality” and “nutrition-income relationship"? I've been going back and forth but I think those are good.
* You wrote a comment about food desert definitions: "This seems like an odd choice since (1) we know that households primarily shop outside of their own zipcode and (2) it deviates from the official definition put forth by the USDA. Is there a reason (other than simplicity) that we can use to justify this choice?" My response is that (1) will be a problem regardless of definition, including with USDA's definition. (USDA definition is at the census tract level, but we know that people shop outside their census tract). I think that a key point that we should try to bring out in the paper (e.g. Section 4.1.1) is exactly this issue that food deserts don’t matter because people shop outside their neighborhood. Am I missing something here though?
Your point (2) seems immenently operationalizable. The problem is that I can't find the USDA definitions for the full 2004-2016 sample. (I looked [here](https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data/).) I don't think we can re-create them ourselves easily. But if you or @Rahkovsky can get these definitions, then great. Or if you have other definitions you want to try in robustness checks to Table 2, then great.
Thanks again for looking at that.

**Comment by huntallcott** [comment]
@mollyschnell , @diamondr @handbury @Rahkovsky @moosedube ,
I made some further edits to stylized facts to reflect updated empirical results. Check out the manuscript.
Key changes:
* Our new approach to the stylized facts figs (using sample average income and taking residuals of age, household size) is a better tag of SES than what we were doing before, and also the HEI is more highly correlated with income than the old HealthIndex. So we now have a top-bottom quartile gap of 0.62 standard deviations. 
* The RMS analysis is a bit different than with the old HealthIndex. Store type was a really good predictor of HealthIndex of UPCs offered. This is less true for HEI of UPCs offered. The individual nutrients are pretty consistent (i.e. when you compare Gladson added sugar content of UPCs offered in RMS stores to the HEI added sugar content, or compare sat fat against sat fat) you get similar results, so I am not super-displeased with the HEI nutrition facts or imputation or measurement error. Instead, it the HEI measures other dietary components that our made-up HealthIndex did not, and it turns out that these vary more across stores within store type than the HealthIndex macronutrients. Furthermore, the store types are not as clearly ordered in terms of healthfulness of supply measured by HEI. Supercenters are now better than grocery, and drug stores are actually pretty good. As a result, I changed and toned down some language in the intro and stylized facts section around this.
* Between Molly and me, we have significantly streamlined the stylized facts section and also the stylized facts appendices. I'm pretty happy with that part of things.

**Comment by Rahkovsky** [comment]
@huntallcott USDA food desert definition is based on the Census tract, but it does not assume that consumers are restricted to their Census tract shopping. It just uses population weighted Census tract centroid as a proxy for the location of the consumer home.  USDA definition is very strict <1 mi to the nearest supermarket in the urban areas and a relatively poor Census tract. 

Personally, I don't think the USDA definition is very good. For the USDA food desert (term is no longer used) has two parts: low-income and low-access. Low income is the poverty rates (at least 20 percent) or median family income (at or below 80 percent of the metropolitan area or State median income) in a census tract. Low access measures are based on the distance to the nearest supermarkets (<1 mi for urban areas and <10 mi to rural areas). There is also an also a modification of the definition to include tracts with at least 100 household without vehicle access. 

See more at:
https://www.ers.usda.gov/webdocs/publications/82101/eib-165.pdf?v=0


I find it difficult to defend this definition. It is not based on the consumption or travelling patterns. In fact we know that most people do not shop in the nearest supermarket. In any case, if you think we need it for robustness I can upload the Census tract data to dropbox.

**Comment by mollyschnell** [comment]
@huntallcott: I went through the SF and RF sections and cut things down further. I've left a few notes here and there in the text—let me know if you have any thoughts! 

[I also added a paragraph on the within-location analysis to the introduction.]
