### ISSUE TITLE
Movers analysis

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#13]
@mollyschnell @diamondr @handbury @moosedube @Rahkovsky ,
Let's use this thread to discuss the movers analysis as needed.

First post: I have updated the movers analysis with the new linearized HEI data. Take a look.
Notice that we now have statistically significant coefficient on local environment. This is bad news in the sense that we were worried that this is biased upwards. There's also some bad news in that the standard errors widened out a bit. The good news is that despite these two things, the bounds on the place effects are still very tight. The main driver of this is that the local environment difference between low-income households and high-income households just isn't that large, and so even if we admit a larger possible effect size, it still doesn't explain much of the nutrition-income relationship.

**Comment by moosedube** [comment]
@mollyschnell @diamondr @handbury @moosedube @Rahkovsky , Not sure who is "officially" in charge of section 4.2 estimates, but I think the decompositions at the end are out of date.  I think the cross-zip moves should be: 0.14*0.12/0.58 = 29%, and the cross-county moves should be: 0.1*.25/0.58  = 4.3%.

**Comment by huntallcott** [comment]
@moosedube that's me still. Sorry. Some of the numbers auto-update, and others don't, and I haven't auto-updated.
All: can I edit the lyx file today? I would like to accept @mollyschnell's excellent comments. Or JP, if you are working still, I can wait. Or we can agree that you will push now and won't edit in the reduced form sections?

**Comment by moosedube** [comment]
I’m all set and committed my comments yesterday.

Best,

JP
