### ISSUE TITLE
Revise in response to QJE reports

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#15]
@handbury @Rahkovsky @mollyschnell @moosedube @diamondr ,
Am I correct that we plan to submit to QJE and then to AER?
My guess is that Larry would send back to a combination of referees that we had on our two papers before. 
It looks like we could easily convert ADD's R2 to R&R, R3's main concerns are moot, and R1 will remain skeptical.

If we are submitting to QJE, then I think it would be useful to review the referee comments and make sure that we have responded to them as much as possible. In looking at the reports from HRS and ADD, it seems as though the ADD QJE reports are particularly relevant for the paper as it reads now. 
(Note that I don't think that we should submit referee responses.)

- [x] JP and Rebecca, can you make sure that the referees' concerns with the demand estimates are answered somewhere in the manuscript?

- [x] I am going to look at the reports and add a few things to the reduced form section. 

- [x] Do any of you see a way to shore up the intro to address R1's comment 1/2?

**Comment by huntallcott** [comment]
@diamondr @moosedube ,

Two questions:
1. In re-reading the referee reports, I realized that I think I can address every single one of the comments on the stylized facts/reduced form/Health Index definition in a short sentence or two. Thus I'm wondering if we actually want to submit a shortened version of a referee response as part of a cover letter to Larry. The file dropbox/FoodDeserts/JournalSubmissions/QJE/QJE Cover Letter.docx is a proposed letter to Larry, and you can see in a couple example places that I wrote one sentence in italics that responds to the referee. 

** Is this something that you think can be done for the comments on the demand estimation sections, including defending the instrument's exclusion restriction and other identification issues? And do you agree that this might actually be helpful? If so, then today I will complete the responses that I can do and leave the rest to you. Let me know.

2. JP, why did you choose the username "moose"?

**Comment by diamondr** [comment]
On it!

**Comment by huntallcott** [comment]
@diamondr @moosedube ,
This afternoon, I have further revised the QJE Cover Letter document to more completely respond to referees. I am closing the doc now. @moosedube, would you be willing to take one more final look at the parts pertaining to the demand model and try to bring it to a close? 
My view is that we just want short answers here, as this is not really an official response document, so it's OK to be brief. You can see that I've done that with much of the doc so far.

**Comment by huntallcott** [comment]
@moosedube just a ping on the above post. Would you be willing to take a final look at QJE Cover Letter.docx in dropbox/JournalSubmissions/QJE/ and make sure everything on the demand model is crisp and reflects our most recent discussions about identification etc.? Many thanks if you can do that.

> @diamondr @moosedube ,
> This afternoon, I have further revised the QJE Cover Letter document to more completely respond to referees. I am closing the doc now. @moosedube, would you be willing to take one more final look at the parts pertaining to the demand model and try to bring it to a close?
> My view is that we just want short answers here, as this is not really an official response document, so it's OK to be brief. You can see that I've done that with much of the doc so far.

**Comment by moosedube** [comment]
I made a few edits, including adding responses to comments 6.3 and 6.4 by referee one. Please take a look.

In re-reading, I worry that we may sound too defensive in our response to point 7 regarding the structural interpretation. We have stated exactly what variation we use to identify our nutrient preferences. The referee has not provided a specific way in which allegedly endogenous nutrient variation would violate the consistency of our estimates. I also disagree with the statement about shelf life. This is absolutely incorrect and defies the logic of households shopping in farmer’s markets (a point beyond the scope of our data).  Many shoppers are suspicious of shelf-stable products. This is why Kraft puts cheese slices in the fridge even though they can technologically speaking sell a shelf-stable version with a very long shelf life. Refrigeration and perishability are often perceived as “healthier.”  Anyhow, all this is beyond scope of paper. But, we need to think about how to respond to this point.

Best,

JP

**Comment by huntallcott** [comment]
Closing this issue, as I think we've revised as much as possible to satisfy the referees.
