### ISSUE TITLE
Defend instrument in demand model

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#16]
The goal of this issue is to modify the paper to improve defense of the instrument, to address referee concerns.
@diamondr this is per our discussion on the phone the other day.

This file has the IV graphics that I mentioned.
[Pages from ALT_Slides.pdf](https://github.com/huntallcott/FoodDeserts/files/2405611/Pages.from.ALT_Slides.pdf)
We had a slightly different set of fixed effects and so maybe some of these are not needed for food deserts, but take a look. Seems like slide 6 might be relevant, possibly others.

I just added a file GitHub\FoodDeserts\Code\Analysis\ModelEstimates\DescribingInstrument.do that has  the code to make these slides. It may need to be modified slightly to get the variable names right, but you'll see the point.

Do you want to take a look and use as you see fit? And let me know if you have questions or if you'd like me to help.
cc @moosedube also.

**Comment by huntallcott** [comment]
@diamondr I used a different naming convention for soda tax paper. In the fooddeserts directory this file is called Dropbox\FoodDeserts\Externals\Calculations\Geographic\CtXYear_Data.dta. If you change it to that, it should work.

**Comment by diamondr** [comment]
Great Thanks. That file doesn't have 2015 and 2016. Any chance you could
update it? I'm happy to do it if you point me to where there code is.
Thanks.

**Comment by huntallcott** [comment]
I just updated it; you should have it once dropbox updates on your end.
Sorry for the confusion.

**Comment by diamondr** [comment]
Awesome, thanks!. Btw, what the mean and SD of the health index you use to
normalize everything? Thanks!

**Comment by huntallcott** [comment]
Am headed to airport right now, but I know that it's created in GitHub\FoodDeserts\Code\DataPrep\OtherNielsen\InsertHealthMeasures.do. Thanks much.

**Comment by moosedube** [comment]
I just committed edited version of lyx file to Github with references to latest subsidies in abstract, intro and conclusions. I tried to clean up some of the track changes so you can easily see my latest edits (and Molly’s edits to the intro).

JP

**Comment by huntallcott** [comment]
Rebecca, these new figures and table are nice. I am closing this issue.

**Comment by huntallcott** [comment]
Another question:
3. Figure A14, the first stage regression. The figure note says we have zip-3 fixed effects and product group fixed effects. But line 183 of explore_iv.do (is that the right file?) looks like it uses fixed effects involving the variable inc_cat. Don't we want consistent fixed effects with the main regression, so county and product group?

**Comment by diamondr** [comment]
Re #1: I think pairs of product groups makes sense since it represents the
variation we're actually using. The IV always has country FEs so it takes
out absolute price differences between countries among all product groups.
The pairs do this to. Maybe I should just add a sentence or two saying this?

Re #2: I'm happy to change it. I'm on a plane right now and don't have good
enough internet to pull the data files from dropbox until i get high speed
internet. I'm at a conference today, but I can try to do it tonight.

Re #3: Yes, I need to update those notes. Sorry for missing that. Thanks
for catching it.

**Comment by diamondr** [comment]
Are the county income already CPI deflated? Maybe not?

**Comment by diamondr** [comment]
Should I edit the lyx file now? Turns out plane interent was strong enough
to download what i needed. I updated the regression with county, year, and
product group FEs. Same result.

**Comment by huntallcott** [comment]
* I disagree on 1. The differences between product group pairs is *also* not the variation we are using. Putting these pairs obscures the actual variation that we want people to see. The fact that you wrote the text (correctly, I think) to focus on the spatial variation within product groups (e.g. that produce is cheaper on west coast) suggests to me that this is the variation we want people to understand. 
* There are two county income variables, one of them with "Nominal" in the variable name. The other one is real.
* Yes, feel free to edit that part of the lyx file. Please pull from the repo now and push again ASAP.

**Comment by diamondr** [comment]
Ok I'll make it the other way. Happy to do it if you think its clearer.

**Comment by huntallcott** [comment]
sweet, thanks. let me know when you're done with the lyx file.

**Comment by huntallcott** [comment]
@diamondr, I'm looking at figure 8. I think you said [here](https://github.com/huntallcott/FoodDeserts/issues/14#issuecomment-431386478) that you updated the figure note, but the regression coefficient and standard error are exactly the same. Is that just a coincidence?
Aside: one option is to use the option reportreg or similar, so that this updates automatically?

**Comment by diamondr** [comment]
This is updated.

**Comment by huntallcott** [comment]
@diamondr thanks for your efforts on defending the instrument! Closing this issue.
