### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#17]
@diamondr @moosedube @mollyschnell @handbury @Rahkovsky 

The goal of this issue is to clean up the GitHub repo and dropbox/Externals/ so that there are no legacy files and we are comfortable posting the entire Code/ folder as our replication files.

I just deleted a number of old files that I and others had created. If you disagree, then please consider recovering those old files and putting them on a separate, appropriately named branch. Either way, all these files are obviously stored using the GitHub history.

Please take a quick look and see if you have other legacy files? Then I'll close this issue in a day or two.

**Comment by huntallcott** [comment]
Actually, @diamondr, one more thing:
There are two very old files in Code/DataPrep/RMS/
a. CollapseMovementDatabyUPCStoreYear
b. CreateCounterFactualSupplyUPC

I am not using these. Are you? If not, can you delete?

**Comment by diamondr** [comment]
Deleted! :)

**Comment by handbury** [comment]
ReducedForm/Tables deleted.  Closing issue.

**Comment by huntallcott** [comment]
Minor: @diamondr @moosedube what about Code/Analysis/ModelEstimates/, is this folder clean of outdated files? In particular, I'm wondering about files called beta?_1120.mat.

**Comment by huntallcott** [comment]
And beta2temp.mat?
