### ISSUE TITLE
positioning

### ISSUE THREAD

**Issue by moosedube** [huntallcott/FoodDeserts#23]
@huntallcott @diamondr @handbury @mollyschnell @Rahkovsky 

I wonder if we want to modify the intro to have updated information about total spending on store subsidies.  Check out this link: http://thefoodtrust.org/what-we-do/administrative/hffi-impacts/the-success-of-hffi.

It looks like HFFI has expanded its scope including quite a few state and local projects. At the federal level, they have leveraged over $1 billion privately on 958 healthy food projects.  Given the support of the USDA, I wonder if they have seen this paper which of course has a USDA economist working on it?

Also check this link: http://thefoodtrust.org/what-we-do/administrative/hffi-impacts/evaluating-hffi.
It describes food deserts as "market failures."  It also remarkably describes how they evaluate HFFI, without any reference to evidence or a test for changes in actual nutrient consumption.

**Comment by huntallcott** [comment]
Great. @mollyschnell is it OK to assign this to you? I think the action item just involves updating the sentence and/or footnote describing this stuff, and perhaps updating the citations accordingly.

**Comment by mollyschnell** [comment]
No problem! I can add more details/ new citations when doing the final read-through. Thanks for the updated info @moosedube.

**Comment by huntallcott** [comment]
Thanks @mollyschnell, closing this after your additions to footnote 3.
