### ISSUE TITLE
Molly's final read

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#24]
This is the thread for Molly's final read, per our emails.
One additional thing: I think that your read will be invaluable, but I would suggest you go pretty light on the edits, just focusing on obvious errors or typos or anything big. 
One reason is that there are a ton of "dependencies" now between the referee responses and the paper, e.g. count of pages, table and figure numbers, count of footnotes, and a number of exact quotes, so changing one thing could be more complicated than it might seem.

Post here when you're done? Then I'll resubmit, hopefully ASAP early next week.
Thanks in advance for your work.

**Comment by mollyschnell** [comment]
Sounds good — I'll go very light on the edits. I'm hoping to have this wrapped up by EOD Tuesday at the latest.

**Comment by mollyschnell** [comment]
@huntallcott: I just pushed the draft with minor edits (fixed typos + adjusted language for clarity here and there). I also went through the response documents and checked that the exact quotes/ page numbers still align. I think we're good to go!

**Comment by huntallcott** [comment]
@mollyschnell fantastic. I will accept these changes in the morning!

**Comment by huntallcott** [comment]
@mollyschnell this is truly tremendous. Thanks again. Closing this issue.
