### ISSUE TITLE
Finalize op-ed

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#25]
@moosedube,
@mollyschnell and I met last week and have arrived at a draft of the op-ed that we're happy with. It's in dropbox/FoodDeserts/FoodDesertOpEd/Food deserts op-ed.docx.
Can you take a look? 
The goal of this issue is for you to make any changes you desire and for us to complete the draft.
Then we can open another issue for submitting this to outlets.

**Comment by huntallcott** [comment]
@mollyschnell @moosedube,
moving our email conversation to GitHub.
1. Casual writing: I am getting the sense that this is utterly crucial for op-ed writing. Contractions and beginning sentences with "But" or "And" is totally OK.
2. Why nothing about nutrition education? My sense is that soda taxes are way more effective than nutrition education, as a practical matter. But I'm happy for you to add something if you can supply a hyperlink to an intervention that you really would like to see scaled up.
3. Simultaneity: I added this: “Basic economic logic would foreshadow our result. The food desert idea is that the lack of supply of healthy foods in food deserts causes lower demand for healthy foods. But in the modern economy, grocers have become amazingly good at selling us exactly the kinds of foods we want to buy. Another story, which our data support, is that lower demand for healthy food is what causes the lack of supply.” I put this after our result because I wanted to lead with the empirical data instead of the theory that got us started on this, as I think normal people might worry that theory would lead us economists to have a bias in how we read the data.
4. It’s now about 50 words too long, but probably OK to go ahead and send out to a newspaper.
5. @moosedube in terms of circulating to newspapers, do you want to work through Booth or NYU? The NYU guy is pretty good, although he is a bit less excited about this one because our results have collectively already been covered by many outlets.
6. Any other thoughts?

**Comment by mollyschnell** [comment]
I like the new part on simultaneity—good call on putting it after the results. I think this looks good to go! Let me know if there's anything else I can help with. Molly

**Comment by moosedube** [comment]
Agreed. I like the tone and flow of the revised document. Happy to help if there is any additional work to be done.

Thanks for taking the lead!

Cheers,

JP
