### ISSUE TITLE
Update/impute nutrition facts through 2016

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#4]
@diamondr ,
Hi. I'm updating our code and data through 2016. There is a file called Dropbox/FoodDeserts/Externals/Calculations/NutritionFacts/hms_upcs_with_nut_facts_imputed.dta, which I pulled over (along with everything else) from our old ADD directory. 
I think that this does not include any UPCs added more recently, and since we are adding 2016 data, there will be some missing matches. 
It was prepared by Code/DataPrep/NutritionFacts/PrepGladsonNutritionFacts.do, but you'll see that this file just pulls over some other file that Katie prepared at some point, and so the imputation only covers old data, maybe even just the original 2004-2013 data, now that I think of it.
I recall that you had worked on the nutrition facts stuff before, and I'd appreciate it if you'd be willing to take a look again? Would you be willing to take a look at any records of Katie's files and update PrepGladsonNutritionFacts.do?

**Comment by diamondr** [comment]
Will take a look

**Comment by diamondr** [comment]
The imputation code is up to date and run through 2016.

**Comment by huntallcott** [comment]
@diamondr thanks for doing this. Just to double-check, we should now re-make HHxGroup for the demand estimates given the new nutrition facts. Do you want to do that or should I?

**Comment by diamondr** [comment]
Already done!
