### ISSUE TITLE
Decide whether to use nominal income bins or sample average real income bins

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#8]
@handbury @mollyschnell @diamondr ,
A few weeks ago we discussed whether to use nominal income bins vs. sample average real income bins for stylized facts, which will then affect how we split the sample for the demand model as discussed last night in #3. 

ADD originally used current-year nominal income to group households because those allow us to use the bins we get directly from Nielsen. If we deflate to real income, then we end up combining income groups in weird ways -- for example, all households in the $60-70k income bin in 2016 might get classified in the same income group as all households in the $50-60k income bin in 2008 and before. 

The other day, we decided that we would use household sample average income, which I presume would be sample average *real* income. Two reasons for this are (1) there has been some inflation and also income growth from 2004-2016, and (2) we thought that this would deal better with measurement error. 

It turns out that it makes very little difference in the slopes and trends. Our healthfulness x income figure with [contemporaneous nominal income](https://github.com/huntallcott/FoodDeserts/blob/master/Output/StylizedFacts/Figures/Healthfulness_Income.pdf) is very similar to that with [sample average real income](https://github.com/huntallcott/FoodDeserts/blob/master/Output/StylizedFacts/Figures/HealthIndex_HHAvIncomexYear.pdf). The trends with [contemporaneous nominal income](https://github.com/huntallcott/FoodDeserts/blob/master/Output/StylizedFacts/Figures/HealthIndex_IncomexYear.pdf) are also very similar to the trends with [sample average real income](https://github.com/huntallcott/FoodDeserts/blob/master/Output/StylizedFacts/Figures/HealthIndex_HHAvIncomexYear.pdf). In fact, the nominal income figures look smoother to me, probably as a result of the awkward bin combinations discussed above, and smoothness is almost certainly more factually accurate in this case.

I propose we stick to nominal income for our figures and demand model quartile cutoffs. Is this OK?

**Comment by diamondr** [comment]
Ok.

**Comment by handbury** [comment]
Sounds good.

On Jun 15, 2018, at 2:11 PM, diamondr <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok.

**Comment by mollyschnell** [comment]
Sounds good to me as well.
